### ISSUE TITLE
Starting VM show me virtual console 7

### ISSUE THREAD

**Issue by grevius5** [joeknock90/Single-GPU-Passthrough#10]
Hi, I follow all your steps in the manual but I have a problem. When I start the VM my desktop disappear and I see only the virtual console 7.
If I start the script by hand with sudo i can see only a black desktop, and of course, no VM because is not started by anyone.
In my start script, I've also added the systemctl stop lightdm.service.
What can be the problem?

**Comment by grevius5** [comment]
This is my start.sh output:
`/etc/libvirt/hooks/qemu.d/macOS-Simple-KVM/prepare/begin/start.sh: riga 11: /sys/class/vtconsole/vtcon1/bind: File o directory non esistente
  2 /etc/libvirt/hooks/qemu.d/macOS-Simple-KVM/prepare/begin/start.sh: riga 14: echo: errore in scrittura: Nessun device corrisponde
  3 Device pci_0000_01_00_0 detached
`
/sys/class/vtconsole/vtcon1/bind -> no such file or directory 
echo efi-framebuffer.0 > /sys/bus/platform/drivers/efi-framebuffer/unbind -> no device found

**Comment by Schokobecher** [comment]
`in scrittura: Nessun device corrisponde 3 Device pci_0000_01_00_0 detached`

You need to adjust the PCI IDs for your GPU + Audio :)
