### ISSUE TITLE
Start.sh not running

### ISSUE THREAD

**Issue by Schokobecher** [joeknock90/Single-GPU-Passthrough#11]
Hey,

just tried this setup and have some issues. I ran the start.sh via SSH (for debugging) and this is what I get:

> [schoko@schoko-desktop ~]$ sudo /etc/libvirt/hooks/qemu.d/win10/prepare/begin/start.sh 
> + systemctl stop x11vnc.service
> Failed to stop x11vnc.service: Unit x11vnc.service not loaded.
> + systemctl stop sddm.service
> + echo 0
> + echo 0
> + echo efi-framebuffer.0
> + sleep 2
> + modprobe -r nvidia_drm
> modprobe: FATAL: Module nvidia_drm is in use.
> + modprobe -r nvidia_modeset
> modprobe: FATAL: Module nvidia_modeset is in use.
> + modprobe -r nvidia_uvm
> + modprobe -r nvidia
> modprobe: FATAL: Module nvidia is in use.
> + modprobe -r ipmi_devintf
> + modprobe -r ipmi_msghandler
> modprobe: FATAL: Module ipmi_msghandler is in use.
> + virsh nodedev-detach pci_0000_2e_00_0

It then hangs indefinitely trying to detach my GTX 1060

running `sudo virsh nodedev-detach pci_0000_2e_00_0`
results in the same.

I found this issue but it's closed without any resolution :(

https://gitlab.com/YuriAlek/vfio/issues/3

**Comment by joeknock90** [comment]
Try changing sleep to be longer. Sometimes there's a race condition when unbinding the framebuffer.

**Comment by Schokobecher** [comment]
That was the exact issue :)
I bumped it up to 10s and it worked.

Time to fiddle some more till the 2nd GPU arrives, thank you so much!

**Comment by joeknock90** [comment]
Glad it worked. 10s seems like a bit of overkill but if it works for you it works for me!
