### ISSUE TITLE
Can I run this on an AMD GPU too?

### ISSUE THREAD

**Issue by senkivalaki** [joeknock90/Single-GPU-Passthrough#14]
Hi! 
My father just recently gave me an Intel NUC(NUC8i5INH), and said to me, that it does not matter how, but I should put macOs onto it, that must be useable, and must perform correctly, and if I succeed, I get to keep the NUC. 
I have failed multiple times with installing any version of OSX, or MacOS natively, so, since I gave that up, I turned towards virtualisation. The only problem is, that it does not matter how much I try, I can't find any way to properly do this single GPU passthrough on the amd card that is inside. 
Btw, I am currently running Pop! OS's latest version, which is 20.04 LTS. If it is not compatible, I can replace it with any other distro anytime. 
Any help is apprechiated. 
Thanks.

**Comment by joeknock90** [comment]
I love this story. I think it depends on what AMD GPU. The process should be similar, but you shouldn't have to patch the boot rom. I have heard reports that it does work.

**Comment by joeknock90** [comment]
Might be difficult in a NUC if it's built in though.
