### ISSUE TITLE
Include manual hex editing guide

### ISSUE THREAD

**Issue by droidman** [joeknock90/Single-GPU-Passthrough#2]
You can manually patch the graphics card BIOS for GTX 5,6,7,8,9, and 10 series cards instead of using NVIDIA vBIOS VFIO Patcher which limits support to the 10 series. 

**Step 1** Download hex editor of your choice.

**Step 2** Download a copy of your video cards bios or dump it using a tool of your choice

**Step 3** Open the VBIOS in a hex editor and search in the strings for the line including "VIDEO" that starts with a "U"
![search video](https://user-images.githubusercontent.com/3674090/44610184-aa879c00-a7ea-11e8-9772-408e807aea02.png)

**Step 4** Delete all code above this line 
![removed](https://user-images.githubusercontent.com/3674090/44610217-c4c17a00-a7ea-11e8-908d-b988644681e3.png)

**Step 5** Save and continue at [3 in the main guide](https://github.com/joeknock90/Single-GPU-Passthrough#patching-the-gpu-rom-for-the-vm).

**Comment by joeknock90** [comment]
I'll add this in the appropriate spot. Thanks!

**Comment by joeknock90** [comment]
Could you recommend a good hex editor for Linux? This is something I'm not terribly familiar with.

**Comment by droidman** [comment]
[Bless](https://github.com/bwrsandman/Bless) is a good editor for linux, it's included in most repos package managers.
