### ISSUE TITLE
Work flawlessly (X79 Xeon + GTX 650Ti, Ubuntu 20.04 + Windows 10 2004)

### ISSUE THREAD

**Issue by brokeDude2901** [joeknock90/Single-GPU-Passthrough#29]
Mounting the GPU bios dump as a fake CD ROM SATA device to overcome the cannot load ROM thing
However I'm new and I don't know how to passthrough USB devices

**Comment by joeknock90** [comment]
Read up on how to pass through USB devices. There are a ton of resources out there.
