### ISSUE TITLE
Any way to make this work with iGPUs?

### ISSUE THREAD

**Issue by Gymnae** [joeknock90/Single-GPU-Passthrough#3]
Hey there,
great post, it Looks like a promising path.
I wondered if this could work for iGPU Setups, where the dGPU is connected MUXless to the iGPU, for example with NVIDIA Optimus Laptops.
I wouldn't mind running the host headless, as Long as the iGPU can be used to run a guest, MacOS or Windows, with acceleration.

**Comment by joeknock90** [comment]
You know. I'm really not sure, and I don't have an optimus laptop to test. 

I've seems some posts on reddit.com/r/VFIO mentioning MUXless setups. Running the host headless might work (if you're looking to just have Windows/Mac not touch bare hardware). But that's entirely speculation on my part. 

You would probably have to ask there. If you figure something out I wouldn't feel quite comfortable adding instructions to the readme as I would have no way of testing that setup. 

I'm definitely interested in whatever you might find though.

**Comment by Gymnae** [comment]
It seems if someone gets MUXless to work, it's a pro and the solution hacky. The iGPU has to push the Pixels in a muxless setup, as I understand. Thus an X Server needs to talk to it.
I'll let you know if I ever make it work - it's good call to leave it out of this guide, as it's nto in Focus.
