### ISSUE TITLE
[QUESTION] Will this work with an RX 580?

### ISSUE THREAD

**Issue by yourmom-jpeg** [joeknock90/Single-GPU-Passthrough#36]
Hi,

I’ve wanted to do a KVM passthrough for so long. I recently upgraded my system to a Ryzen 5 1600, 16GB of RAM, and an RX 580 8GB. This guide mentions nothing about AMD cards and I am worried about ROM patching because I don’t want my $200+ GPU to become a brick with fans attached. Is ROM patching only for Nvidia cards? 

The last time I tried such a thing I used another guide and after I booted up the VM, my screen turned black and never came back on until I hard restarted my computer, which made the computer boot normally.

I just installed Fedora and am hoping to try it again. Is it possible?

**Comment by duramson** [comment]
As far a i know ROM Patching is only necessary for Nvidia Cards. Also you don't flash the patched ROM back into your Card. Its only for the VM.

**Comment by joeknock90** [comment]
It might be? I don't know, and I can't because I don't have any AMD cards. Try it and let me know what you find.
