### ISSUE TITLE
Black Screen upon VM Activation

### ISSUE THREAD

**Issue by Spudnik1** [joeknock90/Single-GPU-Passthrough#4]
When I activate my VM in virt-manager, I get a black screen, due to the display manager being stopped, and nothing else happens. My VM does not show up.

I configured everything according the "PCI passthrough via OVMF" Arch Wiki page as seen [here](https://wiki.archlinux.org/index.php/PCI_passthrough_via_OVMF), and skipped over the "Isolating the GPU" section as seen [here](https://wiki.archlinux.org/index.php/PCI_passthrough_via_OVMF#Isolating_the_GPU).

I have a working Windows 10 QEMU/KVM with virt-manager, but the display resolution is in 800x600 64hz (My monitor is 1080p 144Hz). This is likely due to no GPU being passed through.

If there are any logs you want from me, just tell me.

**Comment by joeknock90** [comment]
Hey, sorry to get back to you late. 

So you have the VM working in QEMU. DId you remove the Spice and QXL displays before booting up with the graphics card passed through? 

I've noticed that when I boot with a QXL and Spice display it sets that as the primary monitor and doesn't configure the other as a secondary at all.

**Comment by Spudnik1** [comment]
Hi,
I don't have access to my PC until Wednesday, I'll get back to you then.

**Comment by Spudnik1** [comment]
Hi,
I tried removing the Spice and QXL displays from the "Virtual Harware" and I still get a black screen.

What I have setup is my Monitor's Displayport input is my NVIDIA GPU (Main Display), and my Monitor's HDMI input is my Intel iGPU. Is this correct way to do GPU passthrough?
When the VM starts, should it remain on the main DP input, or should it switch input to HDMI?

**Comment by joeknock90** [comment]
Don't connect to the iGPU. You are passing through the Nvidia GPU so that is where the video will be coming from!

Connect the DP to the Nvidia gpu and let me know what happens. If all is well you should get video!

**Comment by Spudnik1** [comment]
Ok, I have my DP input in my NVIDIA GPU plugged, and I did for all the times I've tried this. I removed Spice and QXL and I still get a black screen, any suggestions?

**Comment by joeknock90** [comment]
Do you have another device to SSH into the machine to verify that the VM is running?

**Comment by joeknock90** [comment]
Also, consider trying this if you have an SSH client. 

Try running the start script manually, and seeing what sort of output you get. If the script completely properly, start the VM from SSH and see what happens. If this script doesn't start properly... then post the script you are using (I assume it's the one I have in the README but maybe we can make some adjustments).

Also! What display-manager are you using?

**Comment by Spudnik1** [comment]
Yes I do, give me 1 sec

**Comment by Spudnik1** [comment]
Here is the output of the revert.sh script, I could't get an output for the start.sh script. All I got was a black screen on my main pc, and no output on the ssh terminal on my laptop, I only get the white block-cursor stuck.

https://pastebin.com/tedmXLL4.

Also how would I check if the VM is running on my host PC?

**Comment by joeknock90** [comment]
The start script is the one we are going to need to see output from. 

Did you run the start script from the SSH session? If it isn't outputting anything that's the problem. 

You can check if the vm is running by using virsh:

`sudo virsh list`

**Comment by Spudnik1** [comment]
Ok if I don't run start.sh as sudo, I get an output:
https://pastebin.com/qtcJNxrq

**Comment by Spudnik1** [comment]
Here is my start.sh and revert.sh scripts:
https://pastebin.com/CNeqiXSd
https://pastebin.com/36MNk0qC

**Comment by Spudnik1** [comment]
Also here is my QEMU win10.xml:
https://pastebin.com/9vx23SvM

**Comment by fisherwise** [comment]
Hi @Spudnik1 ,
Did you get this resolved? I'm following the arch wiki as well but instead of making a vm using virt-manager I'm following Yuri's guide and start from QEMU. My QEMU output is fine but I've a black screen

**Comment by FearghalH** [comment]
@fisherwise, sorry, I gave up on it years ago, and opted for a dual boot instead.

**Comment by Spudnik1** [comment]
@fisherwise, sorry, I gave up on it years ago, I opted for a dual boot instead.

**Comment by fisherwise** [comment]
thanks for reply!

**Comment by HoshiYamazaki** [comment]
> thanks for reply!

Do you got fixed that :D ? I have the same issue on r5 3600/rx5700 XT.

**Comment by fisherwise** [comment]
> > thanks for reply!
> 
> Do you got fixed that :D ? I have the same issue on r5 3600/rx5700 XT.

nope, i got another gpu but eventually I switched to intel which has an iGPU
