### ISSUE TITLE
KVM/QEMU Crash?

### ISSUE THREAD

**Issue by Stetsed** [joeknock90/Single-GPU-Passthrough#40]
So basically, I have followed the tutorial step by step, running ubuntu 20.04 btw.

I followed all the steps I wrote my own startup.sh and the rest of that stuff. And for whatever reason whenever I Start the VM it does nothing. Then when I restart the Virt-Manager it says "KVM/QEMU-- Connecting..." and that stays till I restart my PC.

I checked logs and I do not see anything in them. If you guys got any idear please say.

Edit: I think I found the log?
(I just catted it then piped it to the below file)
[ok.txt](https://github.com/joeknock90/Single-GPU-Passthrough/files/6156381/ok.txt)

**Comment by joeknock90** [comment]
Yeah libvirt is probably crashing here. 

Best thing to do is to ssh into your machine in some way and try to see what the libvirt daemon does by preforming the process manually:

1. SSH in
2. Run the start script with debugging on
3. See if that completes properly
4. If that completes properly, run the vm with virsh start {vmname}
5. See what happens there

If it fails at step 3 and the script isn't running properly or not unbinding the GPU properly, it's most likely about changing the sleep command to make it a bit longer.

**Comment by Stetsed** [comment]
I am planning to run it under manjaro(was doing it on debian) and follow the tutorial by muta and hope that works.

The main thing I think is the problem is the cluster fuck known as Nvidia Drivers. It's an absolute shitshow. Drivers are interconnected etc etc etc

**Comment by Stetsed** [comment]
Ok so, I just did as you said. And it seems to be getting stuck at unloading the audio.
