### ISSUE TITLE
Black screen after starting the VM

### ISSUE THREAD

**Issue by zentros** [joeknock90/Single-GPU-Passthrough#41]
**Specs :**

- GPU : RTX 2060
- CPU : i5-9400f

**My start script :**
`  GNU nano 5.6      /etc/libvirt/hooks/qemu.d/win10/prepare/begin/start.sh                 
set -x

source "/etc/libvirt/hooks/kvm.conf"

systemctl stop ssdm.service

echo 0 > /sys/class/vtconsole/vtcon0/bind
echo 0 > /sys/class/vtconsole/vtcon1/bind

echo efi-framebuffer.0 > /sys/bus/platform/drivers/efi-framebuffer/unbind

sleep 5

modprobe -r nvidia_drm
modprobe -r nvidia_modeset
modprobe -r drm_kms_helper
modprobe -r nvidia
modprobe -r i2c_nvidia_gpu
modprobe -r drm
modprobe -r nvidia_uvm

virsh nodedev-detach pci_0000_01_00_0
virsh nodedev-detach pci_0000_01_00_1
virsh nodedev-detach pci_0000_01_00_2
virsh nodedev-detach pci_0000_01_00_3

modprobe vfio
modprobe vfio_pci
modprobe vfio_iommu_type1
`

**My stop script :**
`set -x

source "/etc/libvirt/hooks/kvm.conf"

modprobe -r vfio_pci
modprobe -r vfio_iommu_type1
modprobe -r vfio

virsh nodedev-reattach pci_0000_01_00_0
virsh nodedev-reattach pci_0000_01_00_1
virsh nodedev-reattach pci_0000_01_00_2
virsh nodedev-reattach pci_0000_01_00_3

echo 1 > /sys/class/vtconsole/vtcon0/bind
echo 1 > /sys/class/vtconsole/vtcon1/bind

nvidia-xconfig --query-gpu-info > /dev/null 2>&1

echo "efi-framebuffer.0" > /sys/bus/platform/drivers/efi-framebuffer/bind

modprobe nvidia_drm
modprobe nvidia_modeset
modprobe drm_kms_helper
modprobe nvidia
modprobe drm
modprobe nvidia_umv

systemctl start sddm.service
`

**My libvirt settings :**
`<domain type="kvm">
  <name>win10</name>
  <uuid>be66376b-126f-4868-a504-173fcd214cc8</uuid>
  <metadata>
    <libosinfo:libosinfo xmlns:libosinfo="http://libosinfo.org/xmlns/libvirt/domain/1.0">
      <libosinfo:os id="http://microsoft.com/win/10"/>
    </libosinfo:libosinfo>
  </metadata>
  <memory unit="KiB">8601600</memory>
  <currentMemory unit="KiB">8601600</currentMemory>
  <vcpu placement="static">4</vcpu>
  <os>
    <type arch="x86_64" machine="pc-q35-5.2">hvm</type>
    <loader readonly="yes" type="pflash">/usr/share/edk2-ovmf/x64/OVMF_CODE.fd</loader>
    <nvram>/var/lib/libvirt/qemu/nvram/win10_VARS.fd</nvram>
  </os>
  <features>
    <acpi/>
    <apic/>
    <hyperv>
      <relaxed state="on"/>
      <vapic state="on"/>
      <spinlocks state="on" retries="8191"/>
      <vendor_id state="on" value="bruhmoment"/>
    </hyperv>
    <kvm>
      <hidden state="on"/>
    </kvm>
    <vmport state="off"/>
    <ioapic driver="kvm"/>
  </features>
  <cpu mode="host-model" check="partial">
    <topology sockets="1" dies="1" cores="4" threads="1"/>
  </cpu>
  <clock offset="localtime">
    <timer name="rtc" tickpolicy="catchup"/>
    <timer name="pit" tickpolicy="delay"/>
    <timer name="hpet" present="no"/>
    <timer name="hypervclock" present="yes"/>
  </clock>
  <on_poweroff>destroy</on_poweroff>
  <on_reboot>restart</on_reboot>
  <on_crash>destroy</on_crash>
  <pm>
    <suspend-to-mem enabled="no"/>
    <suspend-to-disk enabled="no"/>
  </pm>
  <devices>
    <emulator>/usr/bin/qemu-system-x86_64</emulator>
    <disk type="file" device="disk">
      <driver name="qemu" type="qcow2"/>
      <source file="/var/lib/libvirt/images/win10.qcow2"/>
      <target dev="sda" bus="sata"/>
      <boot order="2"/>
      <address type="drive" controller="0" bus="0" target="0" unit="0"/>
    </disk>
    <disk type="file" device="cdrom">
      <driver name="qemu" type="raw"/>
      <source file="/home/burgerman/Downloads/Win10_20H2_v2_English_x64.iso"/>
      <target dev="sdb" bus="sata"/>
      <readonly/>
      <boot order="1"/>
      <address type="drive" controller="0" bus="0" target="0" unit="1"/>
    </disk>
    <controller type="usb" index="0" model="qemu-xhci" ports="15">
      <address type="pci" domain="0x0000" bus="0x02" slot="0x00" function="0x0"/>
    </controller>
    <controller type="sata" index="0">
      <address type="pci" domain="0x0000" bus="0x00" slot="0x1f" function="0x2"/>
    </controller>
    <controller type="pci" index="0" model="pcie-root"/>
    <controller type="pci" index="1" model="pcie-root-port">
      <model name="pcie-root-port"/>
      <target chassis="1" port="0x10"/>
      <address type="pci" domain="0x0000" bus="0x00" slot="0x02" function="0x0" multifunction="on"/>
    </controller>
    <controller type="pci" index="2" model="pcie-root-port">
      <model name="pcie-root-port"/>
      <target chassis="2" port="0x11"/>
      <address type="pci" domain="0x0000" bus="0x00" slot="0x02" function="0x1"/>
    </controller>
    <controller type="pci" index="3" model="pcie-root-port">
      <model name="pcie-root-port"/>
      <target chassis="3" port="0x12"/>
      <address type="pci" domain="0x0000" bus="0x00" slot="0x02" function="0x2"/>
    </controller>
    <controller type="pci" index="4" model="pcie-root-port">
      <model name="pcie-root-port"/>
      <target chassis="4" port="0x13"/>
      <address type="pci" domain="0x0000" bus="0x00" slot="0x02" function="0x3"/>
    </controller>
    <controller type="pci" index="5" model="pcie-root-port">
      <model name="pcie-root-port"/>
      <target chassis="5" port="0x14"/>
      <address type="pci" domain="0x0000" bus="0x00" slot="0x02" function="0x4"/>
    </controller>
    <controller type="pci" index="6" model="pcie-root-port">
      <model name="pcie-root-port"/>
      <target chassis="6" port="0x15"/>
      <address type="pci" domain="0x0000" bus="0x00" slot="0x02" function="0x5"/>
    </controller>
    <controller type="pci" index="7" model="pcie-root-port">
      <model name="pcie-root-port"/>
      <target chassis="7" port="0x16"/>
      <address type="pci" domain="0x0000" bus="0x00" slot="0x02" function="0x6"/>
    </controller>
    <controller type="pci" index="8" model="pcie-root-port">
      <model name="pcie-root-port"/>
      <target chassis="8" port="0x17"/>
      <address type="pci" domain="0x0000" bus="0x00" slot="0x02" function="0x7"/>
    </controller>
    <controller type="virtio-serial" index="0">
      <address type="pci" domain="0x0000" bus="0x03" slot="0x00" function="0x0"/>
    </controller>
    <interface type="network">
      <mac address="52:54:00:e1:e1:04"/>
      <source network="default"/>
      <model type="e1000e"/>
      <address type="pci" domain="0x0000" bus="0x01" slot="0x00" function="0x0"/>
    </interface>
    <serial type="pty">
      <target type="isa-serial" port="0">
        <model name="isa-serial"/>
      </target>
    </serial>
    <console type="pty">
      <target type="serial" port="0"/>
    </console>
    <channel type="spicevmc">
      <target type="virtio" name="com.redhat.spice.0"/>
      <address type="virtio-serial" controller="0" bus="0" port="1"/>
    </channel>
    <input type="tablet" bus="usb">
      <address type="usb" bus="0" port="1"/>
    </input>
    <input type="mouse" bus="ps2"/>
    <input type="keyboard" bus="ps2"/>
    <input type="mouse" bus="usb">
      <address type="usb" bus="0" port="4"/>
    </input>
    <input type="keyboard" bus="usb">
      <address type="usb" bus="0" port="5"/>
    </input>
    <sound model="ich9">
      <address type="pci" domain="0x0000" bus="0x00" slot="0x1b" function="0x0"/>
    </sound>
    <hostdev mode="subsystem" type="pci" managed="yes">
      <source>
        <address domain="0x0000" bus="0x01" slot="0x00" function="0x0"/>
      </source>
      <rom file="/home/burgerman/Desktop/patch.rom"/>
      <address type="pci" domain="0x0000" bus="0x05" slot="0x00" function="0x0"/>
    </hostdev>
    <hostdev mode="subsystem" type="pci" managed="yes">
      <source>
        <address domain="0x0000" bus="0x01" slot="0x00" function="0x1"/>
      </source>
      <rom file="/home/burgerman/Desktop/patch.rom"/>
      <address type="pci" domain="0x0000" bus="0x06" slot="0x00" function="0x0"/>
    </hostdev>
    <hostdev mode="subsystem" type="pci" managed="yes">
      <source>
        <address domain="0x0000" bus="0x01" slot="0x00" function="0x2"/>
      </source>
      <rom file="/home/burgerman/Desktop/patch.rom"/>
      <address type="pci" domain="0x0000" bus="0x07" slot="0x00" function="0x0"/>
    </hostdev>
    <hostdev mode="subsystem" type="pci" managed="yes">
      <source>
        <address domain="0x0000" bus="0x01" slot="0x00" function="0x3"/>
      </source>
      <rom file="/home/burgerman/Desktop/patch.rom"/>
      <address type="pci" domain="0x0000" bus="0x08" slot="0x00" function="0x0"/>
    </hostdev>
    <redirdev bus="usb" type="spicevmc">
      <address type="usb" bus="0" port="2"/>
    </redirdev>
    <redirdev bus="usb" type="spicevmc">
      <address type="usb" bus="0" port="3"/>
    </redirdev>
    <memballoon model="virtio">
      <address type="pci" domain="0x0000" bus="0x04" slot="0x00" function="0x0"/>
    </memballoon>
  </devices>
</domain>
`

**_### HELP ME PLEASE_**

**Comment by joeknock90** [comment]
Best way to see what's going on is to SSH into your machine while it's running and run each part manually

1. SSH in
2. Run the start script, make sure it completes sucessfully. If not, let me know where
3. If it runs successfully, run the vm with `virsh start {vmname}`

Let me know what happens there.

**Comment by austra221** [comment]
Hi zentros.

I also have an rtx card and I needed to do one extra command in the script for it to work.
Add `sudo nvidia-persistenced` before `modprobe -r nvidia_drm`.

Without `sudo nvidia-persistenced`, the nvidia-related processes won't shutdown.

I would also recommend setting your wait to 10 seconds instead of 5.
Also, do what joeknock said above.

Good luck

**Comment by zentros** [comment]
> Best way to see what's going on is to SSH into your machine while it's running and run each part manually
> 
>     1. SSH in
> 
>     2. Run the start script, make sure it completes sucessfully. If not, let me know where
> 
>     3. If it runs successfully, run the vm with `virsh start {vmname}`
> 
> 
> Let me know what happens there.

don't have any device to ssh in

**Comment by zentros** [comment]
> Best way to see what's going on is to SSH into your machine while it's running and run each part manually
> 
>     1. SSH in
> 
>     2. Run the start script, make sure it completes sucessfully. If not, let me know where
> 
>     3. If it runs successfully, run the vm with `virsh start {vmname}`
> 
> 
> Let me know what happens there.

don't have any device to ssh in

> Hi zentros.
> 
> I also have an rtx card and I needed to do one extra command in the script for it to work.
> Add `sudo nvidia-persistenced` before `modprobe -r nvidia_drm`.
> 
> Without `sudo nvidia-persistenced`, the nvidia-related processes won't shutdown.
> 
> I would also recommend setting your wait to 10 seconds instead of 5.
> Also, do what joeknock said above.
> 
> Good luck

I added `sudo nvidia-persistenced` still the same issue

**Comment by zentros** [comment]
> Best way to see what's going on is to SSH into your machine while it's running and run each part manually
> 
> 1. SSH in
> 2. Run the start script, make sure it completes sucessfully. If not, let me know where
> 3. If it runs successfully, run the vm with `virsh start {vmname}`
> 
> Let me know what happens there.

Used my brother's phone to ssh in : 
http://imgur.com/gallery/3MPs3X2

**Comment by ricky0178** [comment]
it seems like the drivers for Nvidia gpu aren't installed. you should try doing that first
also, it's better if you remove all of the spice devices, or else nvidia could spit out error 43

**Comment by joeknock90** [comment]
Yeah definitely remove all of the spice devices connected to the VM, I sort of assumed that had been done already. 

The only video device on the VM should be the passed through GPU. 

The start script looks like it runs just fine so that's good.

**Comment by zentros** [comment]
I think i found the problem. Nvidia drivers weren't configured properly. I already removed the spice devices. I'll test the vm tomorrow as it's really late right now

**Comment by zentros** [comment]
> Yeah definitely remove all of the spice devices connected to the VM, I sort of assumed that had been done already.
> 
> The only video device on the VM should be the passed through GPU.
> 
> The start script looks like it runs just fine so that's good.

configured the nvidia drivers. Ssh'd in and this is what i get :
http://imgur.com/gallery/nEzABvC

**Comment by zentros** [comment]
> > Yeah definitely remove all of the spice devices connected to the VM, I sort of assumed that had been done already.
> > The only video device on the VM should be the passed through GPU.
> > The start script looks like it runs just fine so that's good.
> 
> configured the nvidia drivers. Ssh'd in and this is what i get :
> http://imgur.com/gallery/nEzABvC

i managed to make it work, still a black screen tho. no errors while running the script. I also removed spice

**Comment by joeknock90** [comment]
Take out that nvidia-persistenced and try. I don't even know why it's there. Where did you read that it was required?

**Comment by ricky0178** [comment]
> > > Yeah definitely remove all of the spice devices connected to the VM, I sort of assumed that had been done already.
> > > The only video device on the VM should be the passed through GPU.
> > > The start script looks like it runs just fine so that's good.
> > 
> > 
> > configured the nvidia drivers. Ssh'd in and this is what i get :
> > http://imgur.com/gallery/nEzABvC
> 
> i managed to make it work, still a black screen tho. no errors while running the script. I also removed spice

what does starting the vm via `sudo virsh start win10` tell you?

**Comment by joeknock90** [comment]
Something is using the nvidia driver. The script is NOT completing. If you don't take out that sudo nvidia-persistenced command in the start script, the nvidia driver will not be able to unbind from the video card and it will continue to not work.

**Comment by zentros** [comment]
> Something is using the nvidia driver. The script is NOT completing. If you don't take out that sudo nvidia-persistenced command in the start script, the nvidia driver will not be able to unbind from the video card and it will continue to not work.

removed the nvidia-persistenced but now almost all the nvida modules give an error : FATAL ERROR :  Module nvidia still in use

**Comment by joeknock90** [comment]
Try running the script twice. Bear with me here, just curious about something.

**Comment by zentros** [comment]
> Try running the script twice. Bear with me here, just curious about something.

managed to fix it. everything works perfectly now.  The problem was nvidia-settings. It started in the background as soon as i started my pc up. Thanks for all the help

**Comment by imadethisfor1page** [comment]
Nvidia-settings? I know this issue is long old but I might actually need a fix, where?
