### ISSUE TITLE
Audio not working in guest pc

### ISSUE THREAD

**Issue by ricky0178** [joeknock90/Single-GPU-Passthrough#42]
the guide for passing the gpu worked great!
I am having problems with the audio tho, as suggested I'm trying to setup Screm by following the guide on archlinux linked in the README. Although i know the audio packets are working as they are communicating on the shared memory I still have troubles, because when I start the VM no audio passes through whatsoever.
Tried also running the command `speaker-test` while the vm was up and running, but no sound comes out of the headphones connected to the motherboard. It seems like the audio stops working completely when the `systemctl stop display-manager.service` gets executed, and it works back only after I log back into my linux account. Tried also the speaker-test command while executing the start.sh file, and it still stops working when display-manager gets stopped
I've confirmed that Scream gets correctly executed at boot

**Comment by joeknock90** [comment]
Try setting your user to linger services with `sudo loginctl enable-linger username`

That should keep user services running when you kill the display manager.

**Comment by ricky0178** [comment]
Unfortunately that doesn't seem to work either
It does exactly as before, as Pulseaudio seems to completely stop after stopping display-manager

**Comment by joeknock90** [comment]
I'm not sure what I can do here. This is a little bit out of the scope of my GPU guide.
