### ISSUE TITLE
Windows 10 Guest refuses to start

### ISSUE THREAD

**Issue by rupansh** [joeknock90/Single-GPU-Passthrough#45]
### Issue
Guest VM refuses to start after it is shutdown once.
I can notice a flash of tianocore splash but i am not sure.
Rebooting the host fixes the issue
This didn't happen when I initially created the guest (i.e a few hours ago)

### Reproducing
1. Start Guest VM
2. Shutdown Guest
3. Start Guest VM again

### Log
`/var/log/libvirt/qemu/win10.log`
https://del.dog/erimacrapi.txt

`dmesg`
https://del.dog/lolulimayf.txt

Possibly relevant `dmesg` message
`Invalid PCI ROM header signature: expecting 0xaa55, got 0xffff`

### Scripts
`begin.sh`
https://del.dog/asophafuck.sh

`revert.sh`
https://del.dog/katteryfin.sh

### Configs
`kvm.conf`
```
VIRSH_GPU_VIDEO=pci_0000_01_00_0
VIRSH_GPU_AUDIO=pci_0000_01_00_1
```

`win10.xml`
https://del.dog/othomibimi.xml

### VGA Bios
`1050ti.rom` is stock
[vga.zip](https://github.com/joeknock90/Single-GPU-Passthrough/files/6164674/vga.zip)

**Comment by joeknock90** [comment]
Welp this one is a doozy. What sort of hardware are you running? CPU/Mem and stuff.

**Comment by rupansh** [comment]
> Welp this one is a doozy. What sort of hardware are you running? CPU/Mem and stuff.

Mobo: MSI H310 PRO-VD
CPU: i3 8100
GPU: MSI GTX 1050 ti OC Single Fan
Mem: 12GB(8+4) 2133 DDR4
Kernel: 5.11.6

At this point, however the VM is refusing to start at all. Even a reboot (or unplugging) the host doesn't fix :(
dmesg: https://del.dog/ocyvygrery.txt

**Comment by joeknock90** [comment]
There's not much info in dmesg about it, I can see where the card seems to bind to vfio, then it just start's rebinding to the nvidia driver. 

Is there any logs for the machine in ```/var/log/libvirt/qemu/win10.log```?

Otherwise try the process manually through SSH

1. SSH In
2. Run start script manually: ``` sudo sh sudo sh /etc/libvirt/hooks/qemu.d/win10/prepare/begin/start.sh  ```
3. Make sure there are no errors there
4. Start vm: ``` virsh start win10 ```

**Comment by rupansh** [comment]
> There's not much info in dmesg about it, I can see where the card seems to bind to vfio, then it just start's rebinding to the nvidia driver.
> 
> Is there any logs for the machine in `/var/log/libvirt/qemu/win10.log`?
> 
> Otherwise try the process manually through SSH
> 
>     1. SSH In
> 
>     2. Run start script manually: `sudo sh sudo sh /etc/libvirt/hooks/qemu.d/win10/prepare/begin/start.sh `
> 
>     3. Make sure there are no errors there
> 
>     4. Start vm: `virsh start win10`

it seems that the start script had issues
(so did the revert one)
I expected win10.log to have output of both these files but oh well :p
Thanks for the help!
