### ISSUE TITLE
Code43

### ISSUE THREAD

**Issue by geekette86** [joeknock90/Single-GPU-Passthrough#5]
Hi i always get code43 ..i tried everything
make hyperv to off and also kvm hidden and the rom in the pace but nothing .
my card is NVIDIA GT710
Thank you

**Comment by joeknock90** [comment]
Code 43 can be a real pain. Unfortunately, my focus lies more on getting single GPU passthrough running assuming everything else works. 

I would ask for more help on reddit.com/r/vfio. I don't have at GT710 to test with. 

Sorry!

**Comment by Technohacker** [comment]
@geekette86 This would definitely be a necrobump but I followed [this guide](https://www.reddit.com/r/homelab/comments/b5xpua/the_ultimate_beginners_guide_to_gpu_passthrough/) with an Inno3D NVIDIA GT 710 and it worked perfectly (The guide is for Proxmox but can be extended for other Linux hosts). Main things to note were:

1. Make sure the nouveau and nvidia modules are blacklisted
2. Disable vesafb or efifb (depending on whether you have a BIOS/UEFI system respectively)
3. Extract the VGA BIOS with nvflash (if you have a single GPU setup) and patch the file manually (like in this guide) and load it into the PCI passthrough

**Comment by Abh15h3k** [comment]
I dont know if this issue is still active.
For me i only have code 43 when i dont have vendor_id and hidden in the xml when installing windows. ( vendor_id and hidden need to be set before installing windows ). setting them after installing windows give code 43.
