### ISSUE TITLE
Black screen on start of vm

### ISSUE THREAD

**Issue by apernouille** [joeknock90/Single-GPU-Passthrough#51]
Everything seems to work correctly but when launching the virtual machine, the screen turns off and seems to disconnect (no more input on the screen for a few seconds). I then see an underscore which does not flash at the top left of the screen and then a black screen but the screen does not seem to go to sleep, as if the black screen is output from the graphics card.

By checking the logs of my virtual machine I only saw this error: `2021-03-21T21:45:41.246194Z qemu-system-x86_64: vfio_region_write(0000:26:00.0:region1+0x2d52c8, 0xff000000ff080808,8) failed: Device or resource busy` spammed in vm logs

I checked on every forum on the internet and I still have not been able to find a solution, after days of research.

I'd be very thankful for any advice or help !

**Comment by joeknock90** [comment]
Have you gone through any of the troubleshooting steps in the guide? 

If so let me know what you've tried and what the results were.

**Comment by Nixuge** [comment]
Having the exact same issue, the vm apparently worked until the 2nd time i rebooted and now just getting this even when i make a new one

**Comment by Nixuge** [comment]
Btw, went through the troubleshooting steps and:
the "Spice Video" and "QXL video adapter" are removed
Didn't get code 43 but still did the thing from the wiki, still no luck
Tried via ssh, I can run start.sh and then revert.sh and it works just fine, the VM doesn't throw any error/doesn't just hang and libvirt says it's running

**Comment by Nixuge** [comment]
Ok I have no idea what I did but it's working again, the only thing I remember doing is removing the modprobe -r for the nvidia drivers

**Comment by joeknock90** [comment]
Yeah I recently updated that in the guide. 

What Distro are you running?

**Comment by apernouille** [comment]
I solved my problem using : 
`echo 1 > /sys/bus/pci/devices/0000\:26\:00.0/remove
echo 1 > /sys/bus/pci/rescan`
I saw this solution on this page : https://github.com/twenska/pci-passthrough
