### ISSUE TITLE
Cant SSH into host after booting the vm

### ISSUE THREAD

**Issue by jkalter24** [joeknock90/Single-GPU-Passthrough#52]
I created the script and it runs well. only problem is my Network card wont work. I have a usb adapter I use. But I cant ssh from my Windows 10 VM to my Arch Linux host. how can I fix this. is there something I need to add to my start.sh script?

**Comment by joeknock90** [comment]
There's not nearly enough information here, and this is quite a bit outside the scope of Single GPU Passthrough.
