### ISSUE TITLE
Why do we un-probe the Nvidia modules?

### ISSUE THREAD

**Issue by brxken128** [joeknock90/Single-GPU-Passthrough#54]
I haven't been able to find an explanation anywhere so I thought I'd ask here. Why do we need to un-probe the nvidia kernel modules using the hooks? Is the `<rom file="" />` for the VM flashing the VBIOS or is it just providing it for our VM? I have so many questions and haven't been able to find any answers.

**Comment by joeknock90** [comment]
Turns out, we really don't! I've updated the start script to remove that part last night. Previously (about 2 years ago) that was the only way I could get it working consistently. 

The rom file is not flashing the card at all, it's just providing it to the VM. 

I would be happy to answer any other questions.

**Comment by brxken128** [comment]
Thank you! I appreciate the response.

This may be rather dumb, but why do we reload them on release? We never unloaded them in the first place (with the script update), is it just a precautionary measure to ensure they're reloaded?

I really do appreciate all the work you and everyone credited has done, it's awesome!

**Comment by joeknock90** [comment]
```virsh-nodedev detatch``` binds the card to vfio automagically, and in my testing, ```virsh-nodedev reattach``` will properly reload nvidia and nvidia_modeset, but not nvidia_drm and nvidia_uvm, which are required to get the video back up and running. I added nvidia and nvidia_modeset as well just for good measure.

**Comment by brxken128** [comment]
Ahh that makes sense! I appreciate the insight/knowledge, and I apologise for opening a Github issue just to ask these, I wasn't too sure on the best way to contact you :)

**Comment by joeknock90** [comment]
You have nothing to apologize for. It's important to understand the process to troubleshoot it properly. 

I much prefer issues like these to "Help it doesn't work"

**Comment by brxken128** [comment]
I appreciate everything you've provided, the guide works great and the information given is awesome! :)
