### ISSUE TITLE
VFIO Hook Helper not creating a directory tree

### ISSUE THREAD

**Issue by DezzyTee** [joeknock90/Single-GPU-Passthrough#80]
Hi,
first off, thank you for your work!

I'm trying to follow your directions but the Hook Helper doesn't seem to be doing anything. I followed the instructions given except for `sudo service libvirtd restart` since that command doesn't exist. I googled and got the answer that it should be `sudo systemctl restart libvirtd` whicht works out fine but there still is no qemu.d directory created. 

Am I missing something or is there an actual issue?

Running:
 - Manjaro Kernel Version 5.13.19-2
 - KDE Plasma 5.22.5
 - KDE Frameworks 5.87.0

**Comment by joeknock90** [comment]
You might want to take another look at the hook helper guide.

The script does not create those directories for you. It is up to you to create and populate them with your scripts.

Also yes, the service command does not exist by default in Arch or arch derivative distros. I believe other distros keep it around as a compatibility tool for old init scripts.
