### ISSUE TITLE
Internet stops working after passing through gpu

### ISSUE THREAD

**Issue by boofiboi** [joeknock90/Single-GPU-Passthrough#87]
As per title, my internet stops working no matter if its on virtio or e1000e.

[revert.sh](https://pastebin.com/ZCuR8Gr5)
[start.sh](https://pastebin.com/hzPdx0UR)
[my vm .xml](https://pastebin.com/BiGW6ciS)
[dmesg](https://pastebin.com/K8sBBiUu)

Any idea why? I use a RX 5500XT and a R5 1600. I have also checked that my network controller is not in the same iommu group.

With a USB wifi adapter passed through internet does work, but Is very slow as my router is behind 3 concrete walls

**Comment by TR-RBM** [comment]
Have you configured networking yet?
I had the same issue and i had to add a new virtual network and assign it to the VM.
You can add a new virtual network in virt-manager (Edit -> Connection Details -> Virtual Networks)

If you use virtio you may also need to install the [virtio driver](https://github.com/virtio-win/virtio-win-pkg-scripts/blob/master/README.md) in your VM.

Here is an example NAT network which worked for me:
_You will need to change the physical network adapter to your adapter name (may be eth0 or something)_

![grafik](https://user-images.githubusercontent.com/47713618/168464895-fe6fb40b-c3da-482f-9df1-fdd6abf9e7de.png)

**Comment by boofiboi** [comment]
Creating the network adapter always gives me the error that the selected network is already in use, and I cant disable my main network because then the VM's network will die too so.

**Comment by boofiboi** [comment]
nvm it was the subnet, im just stupid.

But yeah, your solution worked perfectly.

Thanks a lot.
